import pandas as pd

df = pd.read_csv("../dataset/portscan.csv")
d2f = pd.read_csv("../dataset/botnet_ares.csv")
d3f = pd.read_csv("../dataset/ddos_loit.csv")
d4f = pd.read_csv("../dataset/dos_golden_eye.csv")
d5f = pd.read_csv("../dataset/dos_hulk.csv")
d6f = pd.read_csv("../dataset/heartbleed.csv")
d7f = pd.read_csv("../dataset/web_sql_injection.csv")
d8f = pd.read_csv("../dataset/monday_benign.csv")
d9f = pd.read_csv("../dataset/tuesday_benign.csv")
d10f = pd.read_csv("../dataset/wednesday_benign.csv")
d11f = pd.read_csv("../dataset/thursday_benign.csv")
d12f = pd.read_csv("../dataset/friday_benign.csv")

print("PORTSCAN:")
print(df.columns.tolist())
print("BOTNET_ARES:")
print(d2f.columns.tolist())
print("DDOS_LOIT:")
print(d3f.columns.tolist())
print("DOS_GOLDEN_EYE:")
print(d4f.columns.tolist())
print("DOS_HULK:")
print(d5f.columns.tolist())
print("HEARTBLEED:")
print(d6f.columns.tolist())
print("WEB_SQL_INJECTION:")
print(d7f.columns.tolist())
print("MONDAY_BENIGN:")
print(d8f.columns.tolist())
print("TUESDAY_BENIGN:")
print(d9f.columns.tolist())
print("WEDNESDAY_BENIGN:")
print(d10f.columns.tolist())
print("THURSDAY_BENIGN:")
print(d11f.columns.tolist())
print("FRIDAY_BENIGN:")
print(d12f.columns.tolist())